site_name: Random Code Documentation
pages:
  - Home: index.md
  - Facebook Swift SDK: facebook-swift.md
  - UIView+Layout.swift: uiview_extensions.md
  - Git Utils: git-utils.md
  - Cocoapods: cocoapods.md

theme: readthedocs